import { 
  collection, 
  doc, 
  getDoc, 
  getDocs, 
  addDoc, 
  updateDoc, 
  deleteDoc, 
  setDoc,
  query, 
  where, 
  orderBy, 
  limit,
  serverTimestamp,
  writeBatch
} from "firebase/firestore";
import { db } from "./firebase";

// Types
export interface User {
  id: string;
  email: string;
  password?: string;
  pin?: string; // 6-digit PIN for quick mobile login
  fullName: string;
  designation?: string;
  department: string;
  phone?: string;
  photoURL?: string;
  officeRoom?: string;
  bio?: string;
  role: "admin" | "teacher";
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Course {
  id: string;
  name: string;
  code: string;
  creditHours: number;
  type: "theory" | "lab";
  year?: number; // Year of study (1-4 for BSc, 1-2 for MSc)
  semester: number;
  program?: string; // "bsc" or "msc" - optional for backward compatibility
  isActive: boolean;
  createdAt: Date;
}

export interface Room {
  id: string;
  roomNumber: string;
  building?: string;
  type: "classroom" | "lab" | "seminar";
  capacity: number;
  isActive: boolean;
  createdAt: Date;
}

export interface TimeSlot {
  id: string;
  label: string;
  startTime: string;
  endTime: string;
  slotOrder: number;
  isBreak: boolean;
  isActive: boolean;
  createdAt: Date;
}

export interface Schedule {
  id: string;
  courseId: string;
  teacherId: string;
  roomId: string;
  timeSlotId: string;
  courseName: string;
  courseCode: string;
  teacherName: string;
  roomNumber: string;
  startTime: string;
  endTime: string;
  dayOfWeek: string;
  semester: number;
  program: string; // "bsc" or "msc"
  classType: "theory" | "lab";
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface ScheduleChange {
  id: string;
  scheduleId: string;
  changeType: "cancelled" | "rescheduled" | "room_changed" | "time_changed" | "extra_class";
  originalDay?: string;
  originalTimeSlotId?: string;
  originalStartTime?: string;
  originalEndTime?: string;
  originalRoomId?: string;
  originalRoomNumber?: string;
  newDay?: string;
  newTimeSlotId?: string;
  newStartTime?: string;
  newEndTime?: string;
  newRoomId?: string;
  newRoomNumber?: string;
  effectiveDate: string;
  reason: string;
  courseName: string;
  courseCode: string;
  teacherId: string;
  teacherName: string;
  semester: number;
  program: string; // "bsc" or "msc"
  changedBy: string;
  changedByName: string;
  isActive: boolean;
  createdAt: Date;
}

export interface Notice {
  id: string;
  title: string;
  content: string;
  category: "academic" | "exam" | "event" | "general" | "schedule_change";
  changeType?: "cancelled" | "rescheduled" | "room_changed" | "time_changed";
  scheduleChangeId?: string;
  affectedSemester?: number;
  affectedProgram?: string; // "bsc" or "msc"
  postedBy: string;
  postedByName: string;
  isPinned: boolean;
  isApproved: boolean;
  isAutoGenerated: boolean;
  attachmentURL?: string;
  expiryDate?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface AcademicCalendarEvent {
  id: string;
  title: string;
  date: Date;
  endDate?: Date;
  eventType: "class" | "exam" | "holiday" | "event";
  description?: string;
  createdAt: Date;
}

export interface SiteSettings {
  id: string;
  siteName?: string;
  siteTagline?: string;
  logoUrl?: string;
  departmentName: string;
  universityName: string;
  contactEmail?: string;
  contactPhone?: string;
  address?: string;
  aboutText?: string;
  facebookURL?: string;
  websiteURL?: string;
  twitterURL?: string;
  libraryURL?: string;
  developerName?: string;
  developerURL?: string;
  updatedAt: Date;
}

export interface LibraryLink {
  id: string;
  degree: string; // "bsc", "msc", or "others"
  semester: number; // 1-8 for BSc, 1-3 for MSc, 0 for Others
  url: string;
  title?: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// Helper to convert Firestore doc to typed object
function docToObj<T>(doc: { id: string; data: () => Record<string, unknown> }): T {
  const data = doc.data();
  return { id: doc.id, ...data } as T;
}

// Helper to convert Firestore timestamp to Date
function timestampToDate(timestamp: unknown): Date {
  if (!timestamp) return new Date(0);
  if (timestamp instanceof Date) return timestamp;
  if (typeof timestamp === "string" || typeof timestamp === "number") {
    const date = new Date(timestamp);
    if (!isNaN(date.getTime())) return date;
  }
  if (typeof timestamp === "object" && timestamp !== null) {
    const ts = timestamp as { seconds?: number; _seconds?: number; nanoseconds?: number };
    const seconds = ts.seconds || ts._seconds || 0;
    if (seconds) return new Date(seconds * 1000);
  }
  return new Date(0);
}

// Notice expiry configuration
const NOTICE_EXPIRY_DAYS = 30; // Notices expire after 30 days (except pinned ones)

// ============ USERS ============
export async function getUser(id: string): Promise<User | null> {
  try {
    const docRef = doc(db, "users", id);
    const docSnap = await getDoc(docRef);
    if (!docSnap.exists()) return null;
    return docToObj<User>(docSnap as unknown as { id: string; data: () => Record<string, unknown> });
  } catch (error) {
    console.error("Error getting user:", error);
    return null;
  }
}

export async function getUserByEmail(email: string): Promise<User | null> {
  try {
    const q = query(collection(db, "users"), where("email", "==", email), limit(1));
    const querySnapshot = await getDocs(q);
    if (querySnapshot.empty) return null;
    const docSnap = querySnapshot.docs[0];
    return docToObj<User>(docSnap as unknown as { id: string; data: () => Record<string, unknown> });
  } catch (error) {
    console.error("Error getting user by email:", error);
    return null;
  }
}

export async function getUserByPin(pin: string): Promise<User | null> {
  try {
    const q = query(collection(db, "users"), where("pin", "==", pin), where("isActive", "==", true), limit(1));
    const querySnapshot = await getDocs(q);
    if (querySnapshot.empty) return null;
    const docSnap = querySnapshot.docs[0];
    return docToObj<User>(docSnap as unknown as { id: string; data: () => Record<string, unknown> });
  } catch (error) {
    console.error("Error getting user by PIN:", error);
    return null;
  }
}

export async function getUsers(role?: string): Promise<User[]> {
  try {
    // Simple query without compound where clauses
    const q = query(collection(db, "users"), where("isActive", "==", true));
    const querySnapshot = await getDocs(q);
    let users = querySnapshot.docs.map((doc) => docToObj<User>(doc as unknown as { id: string; data: () => Record<string, unknown> }));
    
    // Filter in memory
    if (role) {
      users = users.filter(u => u.role === role);
    }
    
    // Sort in memory
    return users.sort((a, b) => a.fullName.localeCompare(b.fullName));
  } catch (error) {
    console.error("Error getting users:", error);
    return [];
  }
}

export async function createUser(data: Omit<User, "id" | "createdAt" | "updatedAt">): Promise<User> {
  const docRef = await addDoc(collection(db, "users"), {
    ...data,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  });
  const newDoc = await getDoc(docRef);
  return docToObj<User>(newDoc as unknown as { id: string; data: () => Record<string, unknown> });
}

export async function updateUser(id: string, data: Partial<User>): Promise<void> {
  const docRef = doc(db, "users", id);
  await updateDoc(docRef, { ...data, updatedAt: serverTimestamp() });
}

export async function deleteUser(id: string): Promise<void> {
  await deleteDoc(doc(db, "users", id));
}

// ============ COURSES ============
export async function getCourses(filters?: { semester?: number; program?: string; type?: string; year?: number }): Promise<Course[]> {
  try {
    const constraints = [where("isActive", "==", true)];
    
    if (filters?.semester) {
      constraints.push(where("semester", "==", filters.semester));
    }
    if (filters?.program) {
      constraints.push(where("program", "==", filters.program));
    }
    if (filters?.year) {
      constraints.push(where("year", "==", filters.year));
    }
    if (filters?.type) {
      constraints.push(where("type", "==", filters.type));
    }
    
    const q = query(collection(db, "courses"), ...constraints);
    const querySnapshot = await getDocs(q);
    const courses = querySnapshot.docs.map((doc) => docToObj<Course>(doc as unknown as { id: string; data: () => Record<string, unknown> }));
    return courses.sort((a, b) => a.code.localeCompare(b.code));
  } catch (error) {
    console.error("Error getting courses:", error);
    return [];
  }
}

export async function getCourse(id: string): Promise<Course | null> {
  try {
    const docRef = doc(db, "courses", id);
    const docSnap = await getDoc(docRef);
    if (!docSnap.exists()) return null;
    return docToObj<Course>(docSnap as unknown as { id: string; data: () => Record<string, unknown> });
  } catch (error) {
    console.error("Error getting course:", error);
    return null;
  }
}

export async function createCourse(data: Omit<Course, "id" | "createdAt">): Promise<Course> {
  const docRef = await addDoc(collection(db, "courses"), {
    ...data,
    createdAt: serverTimestamp(),
  });
  const newDoc = await getDoc(docRef);
  return docToObj<Course>(newDoc as unknown as { id: string; data: () => Record<string, unknown> });
}

// ============ ROOMS ============
export async function getRooms(type?: string): Promise<Room[]> {
  try {
    const constraints = [where("isActive", "==", true)];
    if (type) {
      constraints.push(where("type", "==", type));
    }
    const q = query(collection(db, "rooms"), ...constraints);
    const querySnapshot = await getDocs(q);
    const rooms = querySnapshot.docs.map((doc) => docToObj<Room>(doc as unknown as { id: string; data: () => Record<string, unknown> }));
    return rooms.sort((a, b) => a.roomNumber.localeCompare(b.roomNumber));
  } catch (error) {
    console.error("Error getting rooms:", error);
    return [];
  }
}

export async function getRoom(id: string): Promise<Room | null> {
  try {
    const docRef = doc(db, "rooms", id);
    const docSnap = await getDoc(docRef);
    if (!docSnap.exists()) return null;
    return docToObj<Room>(docSnap as unknown as { id: string; data: () => Record<string, unknown> });
  } catch (error) {
    console.error("Error getting room:", error);
    return null;
  }
}

export async function createRoom(data: Omit<Room, "id" | "createdAt">): Promise<Room> {
  const docRef = await addDoc(collection(db, "rooms"), {
    ...data,
    createdAt: serverTimestamp(),
  });
  const newDoc = await getDoc(docRef);
  return docToObj<Room>(newDoc as unknown as { id: string; data: () => Record<string, unknown> });
}

// ============ TIME SLOTS ============
export async function getTimeSlots(): Promise<TimeSlot[]> {
  try {
    const q = query(collection(db, "timeSlots"), where("isActive", "==", true));
    const querySnapshot = await getDocs(q);
    const slots = querySnapshot.docs.map((doc) => docToObj<TimeSlot>(doc as unknown as { id: string; data: () => Record<string, unknown> }));
    return slots.sort((a, b) => a.slotOrder - b.slotOrder);
  } catch (error) {
    console.error("Error getting time slots:", error);
    return [];
  }
}

export async function createTimeSlot(data: Omit<TimeSlot, "id" | "createdAt">): Promise<TimeSlot> {
  const docRef = await addDoc(collection(db, "timeSlots"), {
    ...data,
    createdAt: serverTimestamp(),
  });
  const newDoc = await getDoc(docRef);
  return docToObj<TimeSlot>(newDoc as unknown as { id: string; data: () => Record<string, unknown> });
}

// ============ SCHEDULES ============
export async function getSchedules(filters?: {
  semester?: number;
  program?: string;
  day?: string;
  teacherId?: string;
}): Promise<Schedule[]> {
  try {
    // Use simple query - only one where clause to avoid index requirements
    const q = query(collection(db, "schedules"), where("isActive", "==", true));
    const querySnapshot = await getDocs(q);
    let schedules = querySnapshot.docs.map((doc) => docToObj<Schedule>(doc as unknown as { id: string; data: () => Record<string, unknown> }));
    
    // Filter in memory
    if (filters?.semester) {
      schedules = schedules.filter(s => s.semester === filters.semester);
    }
    if (filters?.program) {
      schedules = schedules.filter(s => s.program === filters.program);
    }
    if (filters?.day) {
      schedules = schedules.filter(s => s.dayOfWeek === filters.day);
    }
    if (filters?.teacherId) {
      schedules = schedules.filter(s => s.teacherId === filters.teacherId);
    }
    
    return schedules;
  } catch (error) {
    console.error("Error getting schedules:", error);
    return [];
  }
}

export async function getSchedule(id: string): Promise<Schedule | null> {
  try {
    const docRef = doc(db, "schedules", id);
    const docSnap = await getDoc(docRef);
    if (!docSnap.exists()) return null;
    return docToObj<Schedule>(docSnap as unknown as { id: string; data: () => Record<string, unknown> });
  } catch (error) {
    console.error("Error getting schedule:", error);
    return null;
  }
}

export async function createSchedule(data: Omit<Schedule, "id" | "createdAt" | "updatedAt">): Promise<Schedule> {
  const docRef = await addDoc(collection(db, "schedules"), {
    ...data,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  });
  const newDoc = await getDoc(docRef);
  return docToObj<Schedule>(newDoc as unknown as { id: string; data: () => Record<string, unknown> });
}

export async function updateSchedule(id: string, data: Partial<Schedule>): Promise<void> {
  const docRef = doc(db, "schedules", id);
  await updateDoc(docRef, { ...data, updatedAt: serverTimestamp() });
}

// ============ SCHEDULE CHANGES ============
export async function getScheduleChanges(filters?: {
  teacherId?: string;
  effectiveDate?: string;
}): Promise<ScheduleChange[]> {
  try {
    const constraints = [where("isActive", "==", true)];

    if (filters?.teacherId) {
      constraints.push(where("teacherId", "==", filters.teacherId));
    }
    if (filters?.effectiveDate) {
      constraints.push(where("effectiveDate", "==", filters.effectiveDate));
    }

    const q = query(collection(db, "scheduleChanges"), ...constraints);
    const querySnapshot = await getDocs(q);
    const changes = querySnapshot.docs.map((doc) => docToObj<ScheduleChange>(doc as unknown as { id: string; data: () => Record<string, unknown> }));
    // Sort by createdAt descending
    return changes.sort((a, b) => {
      const aTime = a.createdAt ? new Date(a.createdAt as unknown as string).getTime() : 0;
      const bTime = b.createdAt ? new Date(b.createdAt as unknown as string).getTime() : 0;
      return bTime - aTime;
    });
  } catch (error) {
    console.error("Error getting schedule changes:", error);
    return [];
  }
}

export async function createScheduleChange(data: Omit<ScheduleChange, "id" | "createdAt">): Promise<ScheduleChange> {
  const docRef = await addDoc(collection(db, "scheduleChanges"), {
    ...data,
    createdAt: serverTimestamp(),
  });
  const newDoc = await getDoc(docRef);
  return docToObj<ScheduleChange>(newDoc as unknown as { id: string; data: () => Record<string, unknown> });
}

// ============ NOTICES ============
export async function getNotices(filters?: {
  category?: string;
  limitCount?: number;
  pinnedOnly?: boolean;
}): Promise<Notice[]> {
  try {
    const constraints = [where("isApproved", "==", true)];

    if (filters?.category && filters.category !== "all") {
      constraints.push(where("category", "==", filters.category));
    }

    let q = query(collection(db, "notices"), ...constraints);
    
    // Fetch more than needed to account for expired notices that will be filtered
    if (filters?.limitCount) {
      q = query(q, limit(filters.limitCount * 2));
    }

    const querySnapshot = await getDocs(q);
    let notices = querySnapshot.docs.map((doc) => docToObj<Notice>(doc as unknown as { id: string; data: () => Record<string, unknown> }));
    
    // Filter out expired notices (older than NOTICE_EXPIRY_DAYS, except pinned ones)
    const now = new Date();
    const expiryMs = NOTICE_EXPIRY_DAYS * 24 * 60 * 60 * 1000;
    
    notices = notices.filter(notice => {
      // Pinned notices never expire
      if (notice.isPinned) return true;
      // Check if notice has expiry date set
      if (notice.expiryDate) {
        const expiryDate = timestampToDate(notice.expiryDate);
        return expiryDate > now;
      }
      // Check creation date for auto-expiry
      const createdDate = timestampToDate(notice.createdAt);
      const ageMs = now.getTime() - createdDate.getTime();
      return ageMs < expiryMs;
    });
    
    // Sort: pinned first, then by date (newest first)
    notices.sort((a, b) => {
      if (a.isPinned !== b.isPinned) return a.isPinned ? -1 : 1;
      const aTime = timestampToDate(a.createdAt).getTime();
      const bTime = timestampToDate(b.createdAt).getTime();
      return bTime - aTime; // Newest first
    });
    
    // Apply limit after filtering
    if (filters?.limitCount) {
      notices = notices.slice(0, filters.limitCount);
    }
    
    return notices;
  } catch (error) {
    console.error("Error getting notices:", error);
    return [];
  }
}

export async function getNotice(id: string): Promise<Notice | null> {
  try {
    const docRef = doc(db, "notices", id);
    const docSnap = await getDoc(docRef);
    if (!docSnap.exists()) return null;
    return docToObj<Notice>(docSnap as unknown as { id: string; data: () => Record<string, unknown> });
  } catch (error) {
    console.error("Error getting notice:", error);
    return null;
  }
}

export async function createNotice(data: Omit<Notice, "id" | "createdAt" | "updatedAt">): Promise<Notice> {
  const docRef = await addDoc(collection(db, "notices"), {
    ...data,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  });
  const newDoc = await getDoc(docRef);
  return docToObj<Notice>(newDoc as unknown as { id: string; data: () => Record<string, unknown> });
}

export async function updateNotice(id: string, data: Partial<Notice>): Promise<void> {
  const docRef = doc(db, "notices", id);
  await updateDoc(docRef, { ...data, updatedAt: serverTimestamp() });
}

// ============ ACADEMIC CALENDAR ============
export async function getCalendarEvents(type?: string): Promise<AcademicCalendarEvent[]> {
  try {
    const constraints: ReturnType<typeof where>[] = [];
    if (type) {
      constraints.push(where("eventType", "==", type));
    }
    const q = query(collection(db, "academicCalendar"), ...constraints);
    const querySnapshot = await getDocs(q);
    const events = querySnapshot.docs.map((doc) => docToObj<AcademicCalendarEvent>(doc as unknown as { id: string; data: () => Record<string, unknown> }));
    return events.sort((a, b) => {
      const aTime = a.date ? new Date(a.date as unknown as string).getTime() : 0;
      const bTime = b.date ? new Date(b.date as unknown as string).getTime() : 0;
      return aTime - bTime;
    });
  } catch (error) {
    console.error("Error getting calendar events:", error);
    return [];
  }
}

export async function createCalendarEvent(data: Omit<AcademicCalendarEvent, "id" | "createdAt">): Promise<AcademicCalendarEvent> {
  const docRef = await addDoc(collection(db, "academicCalendar"), {
    ...data,
    createdAt: serverTimestamp(),
  });
  const newDoc = await getDoc(docRef);
  return docToObj<AcademicCalendarEvent>(newDoc as unknown as { id: string; data: () => Record<string, unknown> });
}

// ============ SITE SETTINGS ============
export async function getSiteSettings(): Promise<SiteSettings | null> {
  try {
    const docRef = doc(db, "siteSettings", "general");
    const docSnap = await getDoc(docRef);
    if (!docSnap.exists()) return null;
    return docToObj<SiteSettings>(docSnap as unknown as { id: string; data: () => Record<string, unknown> });
  } catch (error) {
    console.error("Error getting site settings:", error);
    return null;
  }
}

export async function updateSiteSettings(data: Partial<SiteSettings>): Promise<void> {
  const docRef = doc(db, "siteSettings", "general");
  // Use set with merge to create if not exists
  await setDoc(docRef, { ...data, id: "general", updatedAt: serverTimestamp() }, { merge: true });
}

// ============ STATS ============
export async function getStats() {
  try {
    const [teachers, courses, rooms, schedules, pendingNotices] = await Promise.all([
      getDocs(query(collection(db, "users"), where("role", "==", "teacher"), where("isActive", "==", true))),
      getDocs(query(collection(db, "courses"), where("isActive", "==", true))),
      getDocs(query(collection(db, "rooms"), where("isActive", "==", true))),
      getDocs(query(collection(db, "schedules"), where("isActive", "==", true))),
      getDocs(query(collection(db, "notices"), where("isApproved", "==", false))),
    ]);

    const currentMonth = new Date().getMonth() + 1;
    const currentYear = new Date().getFullYear();
    const currentSemester = currentMonth >= 1 && currentMonth <= 6 ? `Spring ${currentYear}` : `Fall ${currentYear}`;

    return {
      totalTeachers: teachers.size,
      activeCourses: courses.size,
      totalRooms: rooms.size,
      totalSchedules: schedules.size,
      pendingNotices: pendingNotices.size,
      currentSemester,
    };
  } catch (error) {
    console.error("Error getting stats:", error);
      const currentMonth = new Date().getMonth() + 1;
      const currentYear = new Date().getFullYear();
      return {
        totalTeachers: 0,
        activeCourses: 0,
        totalRooms: 0,
        totalSchedules: 0,
        pendingNotices: 0,
        currentSemester: currentMonth >= 1 && currentMonth <= 6 ? `Spring ${currentYear}` : `Fall ${currentYear}`,
      };
  }
}

// ============ ROOM AVAILABILITY ============
export async function getRoomAvailability(day: string, timeSlotId: string, excludeScheduleId?: string) {
  try {
    const rooms = await getRooms();

    // Get schedules for the given day and time slot
    const q = query(
      collection(db, "schedules"),
      where("dayOfWeek", "==", day),
      where("timeSlotId", "==", timeSlotId),
      where("isActive", "==", true)
    );

    const querySnapshot = await getDocs(q);
    const schedules = querySnapshot.docs.map((doc) => docToObj<Schedule>(doc as unknown as { id: string; data: () => Record<string, unknown> }));

    // Create a map of occupied rooms
    const occupiedRooms = new Map(
      schedules
        .filter((s) => s.id !== excludeScheduleId)
        .map((s) => [
          s.roomId,
          {
            courseCode: s.courseCode,
            courseName: s.courseName,
            teacherName: s.teacherName,
          },
        ])
    );

    // Build availability response
    return rooms.map((room) => ({
      room,
      isAvailable: !occupiedRooms.has(room.id),
      occupiedBy: occupiedRooms.get(room.id) || null,
    }));
  } catch (error) {
    console.error("Error getting room availability:", error);
    return [];
  }
}

// ============ BATCH OPERATIONS ============
export async function batchWrite(operations: Array<{ type: "set" | "update" | "delete"; collection: string; id: string; data?: Record<string, unknown> }>) {
  const batch = writeBatch(db);

  for (const op of operations) {
    const docRef = doc(db, op.collection, op.id);
    if (op.type === "set" && op.data) {
      batch.set(docRef, op.data);
    } else if (op.type === "update" && op.data) {
      batch.update(docRef, op.data);
    } else if (op.type === "delete") {
      batch.delete(docRef);
    }
  }

  await batch.commit();
}

// ============ LIBRARY LINKS ============
export async function getLibraryLinks(degree?: string, semester?: number): Promise<LibraryLink[]> {
  try {
    let q = query(collection(db, "libraryLinks"), where("isActive", "==", true));
    
    if (degree) {
      q = query(q, where("degree", "==", degree));
    }
    if (semester !== undefined) {
      q = query(q, where("semester", "==", semester));
    }
    
    const querySnapshot = await getDocs(q);
    return querySnapshot.docs.map((d) => docToObj<LibraryLink>(d as unknown as { id: string; data: () => Record<string, unknown> }));
  } catch (error) {
    console.error("Error getting library links:", error);
    return [];
  }
}

export async function getLibraryLinkByDegreeSemester(degree: string, semester: number): Promise<LibraryLink | null> {
  try {
    const q = query(
      collection(db, "libraryLinks"),
      where("degree", "==", degree),
      where("semester", "==", semester),
      where("isActive", "==", true),
      limit(1)
    );
    const querySnapshot = await getDocs(q);
    if (querySnapshot.empty) return null;
    return docToObj<LibraryLink>(querySnapshot.docs[0] as unknown as { id: string; data: () => Record<string, unknown> });
  } catch (error) {
    console.error("Error getting library link:", error);
    return null;
  }
}

export async function createLibraryLink(data: Omit<LibraryLink, "id" | "createdAt" | "updatedAt">): Promise<LibraryLink> {
  const docRef = await addDoc(collection(db, "libraryLinks"), {
    ...data,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
  });
  return { id: docRef.id, ...data, createdAt: new Date(), updatedAt: new Date() };
}

export async function updateLibraryLink(id: string, data: Partial<Omit<LibraryLink, "id" | "createdAt">>): Promise<void> {
  await updateDoc(doc(db, "libraryLinks", id), {
    ...data,
    updatedAt: serverTimestamp(),
  });
}

export async function deleteLibraryLink(id: string): Promise<void> {
  await deleteDoc(doc(db, "libraryLinks", id));
}

export async function seedLibraryLinks(): Promise<{ created: number; updated: number; total: number }> {
  const libraryLinks = [
    { degree: 'msc', semester: 1, url: 'https://drive.google.com/drive/folders/1VceHXEDmrp9r1cUlIABu18p3Uf33NmfB?usp=drive_link', title: '1st Semester M.Sc.', isActive: true },
    { degree: 'msc', semester: 2, url: 'https://drive.google.com/drive/folders/101yM-H-_Je9gaI-a0kb8c0tPvv0sCdLP?usp=drive_link', title: '2nd Semester M.Sc.', isActive: true },
    { degree: 'msc', semester: 3, url: 'https://drive.google.com/drive/folders/1Mll30F1tJGwitES0wAQlJb5abPfC2nCS?usp=drive_link', title: '3rd Semester M.Sc.', isActive: true },
    { degree: 'bsc', semester: 1, url: 'https://drive.google.com/drive/folders/1l7zmdJNbk2T_MgpOCkBH_S2khxPbA42W?usp=sharing', title: '1st Semester B.Sc.', isActive: true },
    { degree: 'bsc', semester: 2, url: 'https://drive.google.com/drive/folders/1ahuHL8DyIUFNCiS63JxTwOvkR9SHv3B7?usp=drive_link', title: '2nd Semester B.Sc.', isActive: true },
    { degree: 'bsc', semester: 3, url: 'https://drive.google.com/drive/folders/1-vHXH9nz2fMw9Af7VwrhyjDOPyjIideD?usp=drive_link', title: '3rd Semester B.Sc.', isActive: true },
    { degree: 'bsc', semester: 4, url: 'https://drive.google.com/drive/folders/1FHd6PMDEGgBoOC1gwrigzskaFjiXSiFN?usp=drive_link', title: '4th Semester B.Sc.', isActive: true },
    { degree: 'bsc', semester: 5, url: 'https://drive.google.com/drive/folders/1SY-WSZzgyPVXDFqHX8FanOVXjkNGxlN_?usp=drive_link', title: '5th Semester B.Sc.', isActive: true },
    { degree: 'bsc', semester: 6, url: 'https://drive.google.com/drive/folders/1wFirn1sbteUvygvuxFIIQrCcXme6-rwI?usp=drive_link', title: '6th Semester B.Sc.', isActive: true },
    { degree: 'bsc', semester: 7, url: 'https://drive.google.com/drive/folders/1NVqjlf3UgySV8Z2lgbwmWS-vkmD0W3hY?usp=drive_link', title: '7th Semester B.Sc.', isActive: true },
    { degree: 'bsc', semester: 8, url: 'https://drive.google.com/drive/folders/10sCVbVJracEi448rZLUopuHbOnZSoKJc?usp=drive_link', title: '8th Semester B.Sc.', isActive: true },
    { degree: 'others', semester: 0, url: 'https://drive.google.com/drive/folders/1_Ag7tHC_yPkQpMSZHNDzdccx8AuLahGh?usp=drive_link', title: 'Others - Additional Resources', isActive: true },
  ];

  let created = 0;
  let updated = 0;

  for (const link of libraryLinks) {
    if (!link.url) continue;

    const existing = await getLibraryLinkByDegreeSemester(link.degree, link.semester);
    
    if (existing) {
      await updateLibraryLink(existing.id, { url: link.url, title: link.title, isActive: true });
      updated++;
    } else {
      await createLibraryLink(link);
      created++;
    }
  }

  const all = await getLibraryLinks();
  return { created, updated, total: all.length };
}
