import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { getNotices, createNotice, getNotice } from "@/lib/firebase-services";
import { doc, updateDoc, deleteDoc, serverTimestamp } from "firebase/firestore";
import { db } from "@/lib/firebase";

// GET - Fetch all notices
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const noticeId = searchParams.get("id");
    const category = searchParams.get("category");
    const limitCount = searchParams.get("limit");
    const pinned = searchParams.get("pinned");

    // Single notice fetch
    if (noticeId) {
      const notice = await getNotice(noticeId);
      if (!notice) {
        return NextResponse.json({ success: false, error: "Notice not found" }, { status: 404 });
      }
      return NextResponse.json({ success: true, data: notice });
    }

    // Build filters
    const filters: {
      category?: string;
      limitCount?: number;
      pinnedOnly?: boolean;
    } = {};

    if (category) filters.category = category;
    if (limitCount) filters.limitCount = parseInt(limitCount);
    if (pinned === "true") filters.pinnedOnly = true;

    // Fetch notices
    const notices = await getNotices(filters);

    return NextResponse.json({ success: true, data: notices });
  } catch (error) {
    console.error("Error fetching notices:", error);
    return NextResponse.json({ success: false, error: "Failed to fetch notices" }, { status: 500 });
  }
}

// POST - Create a new notice (Teachers and Admins can create)
export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { 
      title, 
      content, 
      category, 
      isPinned, 
      affectedYear,
      affectedSemester,
      affectedProgram
    } = body;

    // Teachers can create notices, but they need admin approval (except schedule_change)
    // Admins can create approved notices directly
    const isAdmin = session.user.role === "admin";
    const isScheduleChange = category === "schedule_change";

    // Build notice data, filtering out undefined values
    const noticeData: Record<string, any> = {
      title,
      content,
      category: category || "general",
      isPinned: isPinned || false,
      postedBy: session.user.id,
      postedByName: session.user.name || "Unknown",
      isApproved: isAdmin || isScheduleChange, // Auto-approve for admins or schedule changes
      isAutoGenerated: false,
    };
    
    // Only add optional fields if they have values
    if (affectedYear) noticeData.affectedYear = affectedYear;
    if (affectedSemester) noticeData.affectedSemester = affectedSemester;
    if (affectedProgram) noticeData.affectedProgram = affectedProgram;

    const notice = await createNotice(noticeData);

    return NextResponse.json({ 
      success: true, 
      data: notice, 
      message: isAdmin ? "Notice published successfully" : "Notice submitted for approval" 
    });
  } catch (error) {
    console.error("Error creating notice:", error);
    return NextResponse.json({ success: false, error: "Failed to create notice" }, { status: 500 });
  }
}

// PUT - Update notice (Admin only for approval, teachers can edit their own)
export async function PUT(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    const searchParams = request.nextUrl.searchParams;
    const noticeId = searchParams.get("id");

    if (!noticeId) {
      return NextResponse.json({ success: false, error: "Notice ID required" }, { status: 400 });
    }

    const body = await request.json();
    const docRef = doc(db, "notices", noticeId);
    await updateDoc(docRef, { ...body, updatedAt: serverTimestamp() });

    return NextResponse.json({ success: true, message: "Notice updated successfully" });
  } catch (error) {
    console.error("Error updating notice:", error);
    return NextResponse.json({ success: false, error: "Failed to update notice" }, { status: 500 });
  }
}

// DELETE - Delete notice (Admin only)
export async function DELETE(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.id || session.user.role !== "admin") {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });
    }

    const searchParams = request.nextUrl.searchParams;
    const noticeId = searchParams.get("id");

    if (!noticeId) {
      return NextResponse.json({ success: false, error: "Notice ID required" }, { status: 400 });
    }

    await deleteDoc(doc(db, "notices", noticeId));

    return NextResponse.json({ success: true, message: "Notice deleted successfully" });
  } catch (error) {
    console.error("Error deleting notice:", error);
    return NextResponse.json({ success: false, error: "Failed to delete notice" }, { status: 500 });
  }
}
