import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { db } from "@/lib/db";

// GET - Fetch all schedule changes
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const teacherId = searchParams.get("teacherId");
    const effectiveDate = searchParams.get("effectiveDate");

    const where: Record<string, unknown> = { isActive: true };

    if (teacherId) where.teacherId = teacherId;
    if (effectiveDate) where.effectiveDate = effectiveDate;

    const changes = await db.scheduleChange.findMany({
      where,
      orderBy: { createdAt: "desc" },
    });

    return NextResponse.json({
      success: true,
      data: changes,
    });
  } catch (error) {
    console.error("Error fetching schedule changes:", error);
    return NextResponse.json(
      { success: false, error: "Failed to fetch schedule changes" },
      { status: 500 }
    );
  }
}

// POST - Create a schedule change (cancel, reschedule, etc.)
export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return NextResponse.json(
        { success: false, error: "Unauthorized" },
        { status: 401 }
      );
    }

    const body = await request.json();
    const { scheduleId, changeType, reason, effectiveDate, newDay, newTimeSlotId, newRoomId } = body;

    // Get the original schedule
    const schedule = await db.schedule.findUnique({
      where: { id: scheduleId },
      include: { timeSlot: true, room: true },
    });

    if (!schedule) {
      return NextResponse.json(
        { success: false, error: "Schedule not found" },
        { status: 404 }
      );
    }

    // Check if user is authorized (admin or the teacher themselves)
    const isAuthorized = session.user.role === "admin" || schedule.teacherId === session.user.id;

    if (!isAuthorized) {
      return NextResponse.json(
        { success: false, error: "Unauthorized to modify this schedule" },
        { status: 403 }
      );
    }

    // Get user info
    const user = await db.user.findUnique({
      where: { id: session.user.id },
    });

    // Create schedule change record
    const scheduleChange = await db.scheduleChange.create({
      data: {
        scheduleId,
        changeType,
        originalDay: schedule.dayOfWeek,
        originalTimeSlotId: schedule.timeSlotId,
        originalStartTime: schedule.startTime,
        originalEndTime: schedule.endTime,
        originalRoomId: schedule.roomId,
        originalRoomNumber: schedule.roomNumber,
        newDay,
        newTimeSlotId,
        newRoomId,
        effectiveDate,
        reason,
        courseName: schedule.courseName,
        courseCode: schedule.courseCode,
        teacherId: schedule.teacherId,
        teacherName: schedule.teacherName,
        year: schedule.year,
        semester: schedule.semester,
        section: schedule.section,
        changedBy: session.user.id,
        changedByName: user?.fullName || "Unknown",
      },
    });

    // Get new room number if room changed
    let newRoomNumber = null;
    if (newRoomId) {
      const newRoom = await db.room.findUnique({ where: { id: newRoomId } });
      newRoomNumber = newRoom?.roomNumber;
      
      // Update the schedule change with new room number
      await db.scheduleChange.update({
        where: { id: scheduleChange.id },
        data: { newRoomNumber },
      });
    }

    // Create auto notification
    const notificationTitle = getNotificationTitle(changeType, schedule);
    
    await db.notice.create({
      data: {
        title: notificationTitle,
        content: `${user?.fullName} has ${changeType === "cancelled" ? "cancelled" : "modified"} ${schedule.courseName} (${schedule.courseCode}) on ${effectiveDate}. Reason: ${reason}`,
        category: "schedule_change",
        changeType,
        scheduleChangeId: scheduleChange.id,
        affectedYear: schedule.year,
        affectedSemester: schedule.semester,
        affectedSection: schedule.section,
        postedBy: session.user.id,
        postedByName: user?.fullName || "Unknown",
        isPinned: false,
        isApproved: true, // Auto-approved for schedule changes
        isAutoGenerated: true,
      },
    });

    return NextResponse.json({
      success: true,
      data: scheduleChange,
      message: "Schedule change recorded successfully",
    });
  } catch (error) {
    console.error("Error creating schedule change:", error);
    return NextResponse.json(
      { success: false, error: "Failed to create schedule change" },
      { status: 500 }
    );
  }
}

function getNotificationTitle(changeType: string, schedule: { courseName: string; courseCode: string }): string {
  const titles: Record<string, string> = {
    cancelled: `Class Cancelled: ${schedule.courseName} (${schedule.courseCode})`,
    rescheduled: `Class Rescheduled: ${schedule.courseName} (${schedule.courseCode})`,
    room_changed: `Room Changed: ${schedule.courseName} (${schedule.courseCode})`,
    time_changed: `Time Changed: ${schedule.courseName} (${schedule.courseCode})`,
    extra_class: `Extra Class: ${schedule.courseName} (${schedule.courseCode})`,
  };
  return titles[changeType] || `Schedule Update: ${schedule.courseName}`;
}
