"use client";

import { useEffect, useState, useRef, useCallback } from "react";
import { 
  collection, 
  query, 
  where, 
  onSnapshot,
  Unsubscribe,
  DocumentData
} from "firebase/firestore";
import { db } from "@/lib/firebase";

// Types
export interface Schedule {
  id: string;
  courseId: string;
  teacherId: string;
  roomId: string;
  timeSlotId: string;
  courseName: string;
  courseCode: string;
  teacherName: string;
  roomNumber: string;
  startTime: string;
  endTime: string;
  dayOfWeek: string;
  semester: number;
  program: string; // "bsc" or "msc"
  classType: "theory" | "lab" | "exam";
  isActive: boolean;
  createdAt?: unknown;
  updatedAt?: unknown;
}

export interface ScheduleChange {
  id: string;
  scheduleId: string;
  changeType: "cancelled" | "rescheduled" | "room_changed" | "time_changed" | "extra_class";
  originalDay?: string;
  originalTimeSlotId?: string;
  originalStartTime?: string;
  originalEndTime?: string;
  originalRoomId?: string;
  originalRoomNumber?: string;
  newDay?: string;
  newTimeSlotId?: string;
  newStartTime?: string;
  newEndTime?: string;
  newRoomId?: string;
  newRoomNumber?: string;
  effectiveDate: string;
  reason: string;
  courseName: string;
  courseCode: string;
  teacherId: string;
  teacherName: string;
  semester: number;
  program: string; // "bsc" or "msc"
  changedBy: string;
  changedByName: string;
  isActive: boolean;
  createdAt?: unknown;
}

export interface Notice {
  id: string;
  title: string;
  content: string;
  category: "academic" | "exam" | "event" | "general" | "schedule_change";
  changeType?: "cancelled" | "rescheduled" | "room_changed" | "time_changed";
  scheduleChangeId?: string;
  affectedSemester?: number;
  affectedProgram?: string; // "bsc" or "msc"
  postedBy: string;
  postedByName: string;
  isPinned: boolean;
  isApproved: boolean;
  isAutoGenerated: boolean;
  attachmentURL?: string;
  expiryDate?: Date;
  createdAt?: unknown;
  updatedAt?: unknown;
}

export interface TimeSlot {
  id: string;
  label: string;
  startTime: string;
  endTime: string;
  slotOrder: number;
  isBreak: boolean;
  isActive: boolean;
}

export interface Room {
  id: string;
  roomNumber: string;
  building?: string;
  type: "classroom" | "lab" | "seminar";
  capacity: number;
  isActive: boolean;
}

export interface User {
  id: string;
  email: string;
  fullName: string;
  designation?: string;
  department: string;
  phone?: string;
  photoURL?: string;
  officeRoom?: string;
  bio?: string;
  role: "admin" | "teacher";
  isActive: boolean;
}

export interface Course {
  id: string;
  name: string;
  code: string;
  creditHours: number;
  type: "theory" | "lab";
  semester: number;
  program: string; // "bsc" or "msc"
  isActive: boolean;
}

// Helper to convert Firestore doc to typed object
function docToObj<T>(doc: { id: string; data: () => DocumentData }): T {
  const data = doc.data();
  return { id: doc.id, ...data } as T;
}

// Real-time Schedules Hook
export function useRealtimeSchedules(filters?: {
  semester?: number;
  program?: string;
  day?: string;
  teacherId?: string;
}) {
  const [schedules, setSchedules] = useState<Schedule[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const unsubscribeRef = useRef<Unsubscribe | null>(null);

  useEffect(() => {
    const q = query(collection(db, "schedules"), where("isActive", "==", true));
    
    const unsubscribe = onSnapshot(
      q,
      (querySnapshot) => {
        let data = querySnapshot.docs.map((doc) => 
          docToObj<Schedule>(doc as unknown as { id: string; data: () => DocumentData })
        );
        
        // Apply filters in memory
        if (filters?.semester) {
          data = data.filter(s => s.semester === filters.semester);
        }
        if (filters?.program) {
          data = data.filter(s => s.program === filters.program);
        }
        if (filters?.day) {
          data = data.filter(s => s.dayOfWeek?.toLowerCase() === filters.day!.toLowerCase());
        }
        if (filters?.teacherId) {
          data = data.filter(s => s.teacherId === filters.teacherId);
        }
        
        setSchedules(data);
        setLoading(false);
        setError(null);
      },
      (err) => {
        console.error("Error in schedules snapshot:", err);
        setError(err.message);
        setLoading(false);
      }
    );
    
    unsubscribeRef.current = unsubscribe;
    
    return () => {
      if (unsubscribeRef.current) {
        unsubscribeRef.current();
      }
    };
  }, [filters?.semester, filters?.program, filters?.day, filters?.teacherId]);

  return { schedules, loading, error };
}

// Real-time Schedule Changes Hook
export function useRealtimeScheduleChanges(filters?: {
  teacherId?: string;
  effectiveDate?: string;
}) {
  const [changes, setChanges] = useState<ScheduleChange[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const unsubscribeRef = useRef<Unsubscribe | null>(null);

  useEffect(() => {
    const constraints = [where("isActive", "==", true)];
    
    if (filters?.teacherId) {
      constraints.push(where("teacherId", "==", filters.teacherId));
    }
    if (filters?.effectiveDate) {
      constraints.push(where("effectiveDate", "==", filters.effectiveDate));
    }
    
    const q = query(collection(db, "scheduleChanges"), ...constraints);
    
    const unsubscribe = onSnapshot(
      q,
      (querySnapshot) => {
        let data = querySnapshot.docs.map((doc) => 
          docToObj<ScheduleChange>(doc as unknown as { id: string; data: () => DocumentData })
        );
        
        // Sort by createdAt descending
        data.sort((a, b) => {
          const aTime = a.createdAt ? new Date(a.createdAt as string).getTime() : 0;
          const bTime = b.createdAt ? new Date(b.createdAt as string).getTime() : 0;
          return bTime - aTime;
        });
        
        setChanges(data);
        setLoading(false);
        setError(null);
      },
      (err) => {
        console.error("Error in schedule changes snapshot:", err);
        setError(err.message);
        setLoading(false);
      }
    );
    
    unsubscribeRef.current = unsubscribe;
    
    return () => {
      if (unsubscribeRef.current) {
        unsubscribeRef.current();
      }
    };
  }, [filters?.teacherId, filters?.effectiveDate]);

  return { changes, loading, error };
}

// Real-time Notices Hook
export function useRealtimeNotices(filters?: {
  category?: string;
  limitCount?: number;
  pinnedOnly?: boolean;
}) {
  const [notices, setNotices] = useState<Notice[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const unsubscribeRef = useRef<Unsubscribe | null>(null);

  // Helper to convert Firestore timestamp to Date
  const timestampToDate = (timestamp: unknown): Date => {
    if (!timestamp) return new Date(0);
    if (timestamp instanceof Date) return timestamp;
    if (typeof timestamp === "string" || typeof timestamp === "number") {
      const date = new Date(timestamp);
      if (!isNaN(date.getTime())) return date;
    }
    if (typeof timestamp === "object" && timestamp !== null) {
      const ts = timestamp as { seconds?: number; _seconds?: number };
      const seconds = ts.seconds || ts._seconds || 0;
      if (seconds) return new Date(seconds * 1000);
    }
    return new Date(0);
  };

  // Notice expiry: 30 days (except pinned)
  const NOTICE_EXPIRY_DAYS = 30;
  const expiryMs = NOTICE_EXPIRY_DAYS * 24 * 60 * 60 * 1000;

  useEffect(() => {
    const constraints = [where("isApproved", "==", true)];
    
    if (filters?.category && filters.category !== "all") {
      constraints.push(where("category", "==", filters.category));
    }
    
    const q = query(collection(db, "notices"), ...constraints);
    
    const unsubscribe = onSnapshot(
      q,
      (querySnapshot) => {
        let data = querySnapshot.docs.map((doc) => 
          docToObj<Notice>(doc as unknown as { id: string; data: () => DocumentData })
        );
        
        // Filter out expired notices
        const now = new Date();
        data = data.filter(notice => {
          // Pinned notices never expire
          if (notice.isPinned) return true;
          // Check if notice has expiry date set
          if (notice.expiryDate) {
            const expiryDate = timestampToDate(notice.expiryDate);
            return expiryDate > now;
          }
          // Check creation date for auto-expiry
          const createdDate = timestampToDate(notice.createdAt);
          const ageMs = now.getTime() - createdDate.getTime();
          return ageMs < expiryMs;
        });
        
        // Sort: pinned first, then by date (newest first)
        data.sort((a, b) => {
          if (a.isPinned !== b.isPinned) return a.isPinned ? -1 : 1;
          const aTime = timestampToDate(a.createdAt).getTime();
          const bTime = timestampToDate(b.createdAt).getTime();
          return bTime - aTime;
        });
        
        // Apply limit
        if (filters?.limitCount) {
          data = data.slice(0, filters.limitCount);
        }
        
        setNotices(data);
        setLoading(false);
        setError(null);
      },
      (err) => {
        console.error("Error in notices snapshot:", err);
        setError(err.message);
        setLoading(false);
      }
    );
    
    unsubscribeRef.current = unsubscribe;
    
    return () => {
      if (unsubscribeRef.current) {
        unsubscribeRef.current();
      }
    };
  }, [filters?.category, filters?.limitCount]);

  return { notices, loading, error };
}

// Real-time Time Slots Hook
export function useRealtimeTimeSlots() {
  const [timeSlots, setTimeSlots] = useState<TimeSlot[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const unsubscribeRef = useRef<Unsubscribe | null>(null);

  useEffect(() => {
    const q = query(collection(db, "timeSlots"), where("isActive", "==", true));
    
    const unsubscribe = onSnapshot(
      q,
      (querySnapshot) => {
        const data = querySnapshot.docs.map((doc) => 
          docToObj<TimeSlot>(doc as unknown as { id: string; data: () => DocumentData })
        );
        
        // Sort by slotOrder
        data.sort((a, b) => a.slotOrder - b.slotOrder);
        
        setTimeSlots(data);
        setLoading(false);
        setError(null);
      },
      (err) => {
        console.error("Error in time slots snapshot:", err);
        setError(err.message);
        setLoading(false);
      }
    );
    
    unsubscribeRef.current = unsubscribe;
    
    return () => {
      if (unsubscribeRef.current) {
        unsubscribeRef.current();
      }
    };
  }, []);

  return { timeSlots, loading, error };
}

// Real-time Rooms Hook
export function useRealtimeRooms(type?: string) {
  const [rooms, setRooms] = useState<Room[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const unsubscribeRef = useRef<Unsubscribe | null>(null);

  useEffect(() => {
    const constraints = [where("isActive", "==", true)];
    if (type) {
      constraints.push(where("type", "==", type));
    }
    
    const q = query(collection(db, "rooms"), ...constraints);
    
    const unsubscribe = onSnapshot(
      q,
      (querySnapshot) => {
        const data = querySnapshot.docs.map((doc) => 
          docToObj<Room>(doc as unknown as { id: string; data: () => DocumentData })
        );
        
        // Sort by roomNumber
        data.sort((a, b) => a.roomNumber.localeCompare(b.roomNumber));
        
        setRooms(data);
        setLoading(false);
        setError(null);
      },
      (err) => {
        console.error("Error in rooms snapshot:", err);
        setError(err.message);
        setLoading(false);
      }
    );
    
    unsubscribeRef.current = unsubscribe;
    
    return () => {
      if (unsubscribeRef.current) {
        unsubscribeRef.current();
      }
    };
  }, [type]);

  return { rooms, loading, error };
}

// Real-time Teachers Hook
export function useRealtimeTeachers() {
  const [teachers, setTeachers] = useState<User[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const unsubscribeRef = useRef<Unsubscribe | null>(null);

  useEffect(() => {
    const q = query(
      collection(db, "users"), 
      where("isActive", "==", true),
      where("role", "==", "teacher")
    );
    
    const unsubscribe = onSnapshot(
      q,
      (querySnapshot) => {
        const data = querySnapshot.docs.map((doc) => 
          docToObj<User>(doc as unknown as { id: string; data: () => DocumentData })
        );
        
        // Sort by name
        data.sort((a, b) => a.fullName.localeCompare(b.fullName));
        
        setTeachers(data);
        setLoading(false);
        setError(null);
      },
      (err) => {
        console.error("Error in teachers snapshot:", err);
        setError(err.message);
        setLoading(false);
      }
    );
    
    unsubscribeRef.current = unsubscribe;
    
    return () => {
      if (unsubscribeRef.current) {
        unsubscribeRef.current();
      }
    };
  }, []);

  return { teachers, loading, error };
}

// Real-time Courses Hook
export function useRealtimeCourses(filters?: { semester?: number; program?: string; type?: string }) {
  const [courses, setCourses] = useState<Course[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const unsubscribeRef = useRef<Unsubscribe | null>(null);

  useEffect(() => {
    const constraints = [where("isActive", "==", true)];
    
    if (filters?.semester) {
      constraints.push(where("semester", "==", filters.semester));
    }
    if (filters?.program) {
      constraints.push(where("program", "==", filters.program));
    }
    
    const q = query(collection(db, "courses"), ...constraints);
    
    const unsubscribe = onSnapshot(
      q,
      (querySnapshot) => {
        let data = querySnapshot.docs.map((doc) => 
          docToObj<Course>(doc as unknown as { id: string; data: () => DocumentData })
        );
        
        // Filter by type in memory if needed
        if (filters?.type) {
          data = data.filter(c => c.type === filters.type);
        }
        
        // Sort by code
        data.sort((a, b) => a.code.localeCompare(b.code));
        
        setCourses(data);
        setLoading(false);
        setError(null);
      },
      (err) => {
        console.error("Error in courses snapshot:", err);
        setError(err.message);
        setLoading(false);
      }
    );
    
    unsubscribeRef.current = unsubscribe;
    
    return () => {
      if (unsubscribeRef.current) {
        unsubscribeRef.current();
      }
    };
  }, [filters?.semester, filters?.program, filters?.type]);

  return { courses, loading, error };
}

// Combined hook for dashboard data - all in one
export function useRealtimeDashboardData(teacherId?: string) {
  const { schedules, loading: schedulesLoading } = useRealtimeSchedules(
    teacherId ? { teacherId } : undefined
  );
  const { changes, loading: changesLoading } = useRealtimeScheduleChanges(
    teacherId ? { teacherId } : undefined
  );
  const { notices, loading: noticesLoading } = useRealtimeNotices({ limitCount: 10 });
  const { timeSlots, loading: timeSlotsLoading } = useRealtimeTimeSlots();
  const { rooms, loading: roomsLoading } = useRealtimeRooms();
  
  // Create schedule change map
  const scheduleChangeMap = useCallback(() => {
    const map: Record<string, ScheduleChange> = {};
    changes.forEach((change) => {
      if (change.isActive && change.scheduleId) {
        // Only keep the most recent change per schedule
        if (!map[change.scheduleId] || 
            (change.createdAt && map[change.scheduleId].createdAt &&
             new Date(change.createdAt as string) > new Date(map[change.scheduleId].createdAt as string))) {
          map[change.scheduleId] = change;
        }
      }
    });
    return map;
  }, [changes]);
  
  const changeMap = scheduleChangeMap();
  
  // Get effective schedule (with changes applied)
  const getEffectiveSchedule = useCallback((schedule: Schedule): Schedule => {
    const change = changeMap[schedule.id];
    
    if (change?.changeType === "rescheduled" && change?.isActive) {
      return {
        ...schedule,
        dayOfWeek: change.newDay || schedule.dayOfWeek,
        startTime: change.newStartTime || schedule.startTime,
        endTime: change.newEndTime || schedule.endTime,
        roomNumber: change.newRoomNumber || schedule.roomNumber,
      };
    }
    
    return schedule;
  }, [changeMap]);
  
  // Check if schedule is cancelled
  const isScheduleCancelled = useCallback((scheduleId: string): boolean => {
    const change = changeMap[scheduleId];
    return change?.changeType === "cancelled" && change?.isActive;
  }, [changeMap]);

  return {
    schedules,
    changes,
    changeMap,
    notices,
    timeSlots,
    rooms,
    getEffectiveSchedule,
    isScheduleCancelled,
    loading: schedulesLoading || changesLoading || noticesLoading || timeSlotsLoading || roomsLoading,
  };
}
