// User types
export interface User {
  id: string;
  email: string;
  fullName: string;
  designation: string | null;
  department: string;
  phone: string | null;
  photoURL: string | null;
  officeRoom: string | null;
  bio: string | null;
  role: "admin" | "teacher";
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

// Course types
export interface Course {
  id: string;
  name: string;
  code: string;
  creditHours: number;
  type: "theory" | "lab";
  year: number;
  semester: number;
  isActive: boolean;
}

// Room types
export interface Room {
  id: string;
  roomNumber: string;
  building: string | null;
  type: "classroom" | "lab" | "seminar";
  capacity: number;
  isActive: boolean;
}

// TimeSlot types
export interface TimeSlot {
  id: string;
  label: string;
  startTime: string;
  endTime: string;
  slotOrder: number;
  isBreak: boolean;
  isActive: boolean;
}

// Schedule types
export interface Schedule {
  id: string;
  courseId: string;
  teacherId: string;
  roomId: string;
  timeSlotId: string;
  courseName: string;
  courseCode: string;
  teacherName: string;
  roomNumber: string;
  startTime: string;
  endTime: string;
  dayOfWeek: string;
  year: number;
  semester: number;
  section: string;
  classType: "theory" | "lab";
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  // Additional data for display
  teacher?: User;
  course?: Course;
  room?: Room;
  timeSlot?: TimeSlot;
}

// Schedule Change types
export interface ScheduleChange {
  id: string;
  scheduleId: string;
  changeType: "cancelled" | "rescheduled" | "room_changed" | "time_changed" | "extra_class";
  originalDay: string | null;
  originalTimeSlotId: string | null;
  originalStartTime: string | null;
  originalEndTime: string | null;
  originalRoomId: string | null;
  originalRoomNumber: string | null;
  newDay: string | null;
  newTimeSlotId: string | null;
  newStartTime: string | null;
  newEndTime: string | null;
  newRoomId: string | null;
  newRoomNumber: string | null;
  effectiveDate: string;
  reason: string;
  courseName: string;
  courseCode: string;
  teacherId: string;
  teacherName: string;
  year: number;
  semester: number;
  section: string;
  changedBy: string;
  changedByName: string;
  isActive: boolean;
  createdAt: string;
}

// Notice types
export interface Notice {
  id: string;
  title: string;
  content: string;
  category: "academic" | "exam" | "event" | "general" | "schedule_change";
  changeType?: "cancelled" | "rescheduled" | "room_changed" | "time_changed";
  scheduleChangeId?: string;
  affectedYear?: number;
  affectedSemester?: number;
  affectedSection?: string;
  postedBy: string;
  postedByName: string;
  isPinned: boolean;
  isApproved: boolean;
  isAutoGenerated: boolean;
  attachmentURL?: string;
  expiryDate?: string;
  createdAt: string;
  updatedAt: string;
}

// Academic Calendar types
export interface AcademicCalendar {
  id: string;
  title: string;
  date: string;
  endDate?: string;
  eventType: "class" | "exam" | "holiday" | "event";
  description?: string;
}

// Site Settings types
export interface SiteSettings {
  id: string;
  departmentName: string;
  universityName: string;
  logoURL?: string;
  contactEmail?: string;
  contactPhone?: string;
  address?: string;
  aboutText?: string;
  facebookURL?: string;
  websiteURL?: string;
}

// API Response types
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
}

// Dashboard Stats
export interface DashboardStats {
  totalTeachers: number;
  activeCourses: number;
  totalRooms: number;
  currentSemester: string;
  totalSchedules: number;
  pendingNotices: number;
}

// Room Availability
export interface RoomAvailability {
  room: Room;
  isAvailable: boolean;
  occupiedBy?: {
    courseCode: string;
    courseName: string;
    teacherName: string;
  };
}

// Conflict Check Result
export interface ConflictCheckResult {
  hasConflict: boolean;
  conflictType: "room" | "teacher" | "section" | null;
  conflictingSchedule?: Schedule;
  message: string;
}
